#!/usr/bin/env bash

set -o nounset -o errexit -o noclobber -o pipefail


# Directories
#
# .config
# .emacs.d
# .gnupg
# .ipython
# .local
# .mozilla
# .ssh
# .vim
# Desktop
# Documents
# Downloads
# Pictures
# bin

# Files
#
# .alias
# .bashrc
# .fonts.conf
# .gitconfig
# .profile
# .spacemacs
# .spacemacs.env


FULL_PATH=""


tar --create \
    --verbose \
    --gunzip \
    --force-local \
    --file="archive_output_file_name.tar.gz" \
    --directory="$(dirname "${FULL_PATH}")" \
    "$(basename "${FULL_PATH}")"


# The following is an exemplary command of how to archive your system
# tar -cvpzf backup.tar.gz --exclude=/backup.tar.gz --one-file-system /

