#!/usr/bin/env bash
#
# Archive and compress the immediate subdirectories within
# a specified directory, provided as a script argument, and
# compute the checksums for both the resulting compressed
# archives and the files within each immediate subdirectory.

set -o nounset -o errexit -o noclobber -o pipefail

if [ "${#}" -eq 0 ]; then
    echo "Usage: ${0} DIRECTORY"
    exit 0
elif [ "${#}" -ne 1 ]; then
    echo "Expected 1 argument, got ${#}" >&2
    exit 1
fi

if ! BASE_DIR="$(realpath --canonicalize-existing "${1}")"; then
    echo "Argument is not a valid path: ${1}" >&2
    exit 1
fi

readonly BASE_DIR

if [ ! -d "${BASE_DIR}" ] || [ -L "${BASE_DIR}" ]; then
    echo "Argument must be a regular directory: ${BASE_DIR}" >&2
    exit 1
fi

readonly STASH_CHECKSUMS="${BASE_DIR}/SHA256SUMS"

if [ -e "${STASH_CHECKSUMS}" ]; then
    echo "Checksums file already exists: ${STASH_CHECKSUMS}" >&2
    exit 1
fi

readonly EXPR='s#^\(.\{64\}\)\(\s\{2\}\)'"${BASE_DIR}"'/\(.*\)$#\1\2\3#p'

echo "Base directory: ${BASE_DIR}"

while read -r dir_path; do
    dir_name="$(basename "${dir_path}")"
    stash_dir="${BASE_DIR}/.${dir_name}.stash"

    echo -e "\nCurrent subdirectory: ${dir_name}"

    if [ -d "${stash_dir}" ] || ! mkdir "${stash_dir}"; then
        echo "Unable to create directory: ${stash_dir}" >&2
        exit 1
    fi

    echo "Computing checksums of files in the current subdirectory..."

    find "${dir_path}" -type f -exec sha256sum {} + \
        | sed -n "${EXPR}" > "${stash_dir}/${dir_name}.sha256"

    echo "Archiving and compressing current subdirectory..."

    # compressed archive output
    comparch="${stash_dir}/${dir_name}.tar.bz2"

    tar --create \
        --backup=numbered \
        --force-local \
        --verbose --verbose --verbose \
        --bzip2 \
        --file="${comparch}" \
        --directory="${BASE_DIR}" \
        "${dir_name}" > "${comparch}.log"

    echo "Computing compressed archive checksum..."

    sha256sum "${comparch}" \
        | sed -n "${EXPR//"${BASE_DIR}"/"${stash_dir}"}" > "${comparch}.sha256"

    # Make stash items read-only before archiving them
    find "${stash_dir}" -type f -exec chmod 444 {} +

    # archived stash
    stash="${BASE_DIR}/${dir_name}.stash"

    readarray -t stash_items < <(find "${stash_dir}" -type f -exec basename --multiple {} +)

    echo "Creating stash..."

    tar --create \
        --backup=numbered \
        --force-local \
        --file="${stash}" \
        --directory="${stash_dir}" \
        "${stash_items[@]}"

    chmod 444 "${stash}"

    echo "Computing stash checksum..."

    sha256sum "${stash}" | sed -n "${EXPR}" >> "${STASH_CHECKSUMS}"

done < <(find "${BASE_DIR}" -mindepth 1 -maxdepth 1 -type d)

chmod 444 "${STASH_CHECKSUMS}"

echo "Verifying stash files checksums..."

if ! find "$(dirname "${STASH_CHECKSUMS}")" -name "$(basename "${STASH_CHECKSUMS}")" -type f \
    -execdir sha256sum --check --quiet --status --strict {} +; then
    echo "Stash files failed checksum varification." >&2
    exit 1
fi

echo "Verifying stash items checksums..."

if ! find "${BASE_DIR}" -path "${BASE_DIR}/.*.stash/*.sha256" -type f \
    -execdir sha256sum --check --quiet --status --strict {} +; then
    echo "Failed checksum varification." >&2
    exit 1
fi

echo -e "\nEverything has been successfully stashed away."

